### ISSUE TITLE
Erro ao rodar o build do projeto.

### ISSUE THREAD

**Issue by lucaspdude** [tavareshenrique/go-barber-web#5]
Quando rodo o build do Projeto, os root imports utilizando " ~/ " são ignorados e não funcionam.

A única solução que encontrei para fazer rodar o build, foi refatorar todos os meus imports, utilizando os caminhos absolutos. =(

**Comment by tavareshenrique** [comment]
Retorna algum erro no terminal ao fazer build, @lucaspdude?

**Comment by lucaspdude** [comment]
Eu vou finalizar o issue, por que na realidade não vai ter a ver com o go-barber-web.

Utilizei o boilerplate do projeto para criar uma aplicação para praticar, mas alguma coisa que fiz errado no caminho do desenvolvimento faz com que o build retorne em branco.

Até o momento não descobri qual o problema real é, mas obviamente não é o root import, muito menos algo relacionado ao go-barber-web.
